project:
  type: website
  output-dir: docs

website:
  title: "Oliver Witt"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: "About Me"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Interests"
        href: interests.qmd
      - text: Resume
        href: files/Witt_Resume_MEDS_template_pdf.pdf
        target: _blank
        


format:
  html:
    theme: 
      light: minty
    css: styles.css
    toc: true
    page-layout: full



