project:
  type: website
  output-dir: docs

website:
  title: "Oliver Witt"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About Me"
      - href: projects.qmd
        text: "Projects"
      - href: interests.qmd
        text: "Interests"
      - text: Resume
        href: files/Witt_Resume_MEDS_template_pdf.pdf
        target: _blank
        


format:
  html:
    theme: 
      light: minty
    css: styles.css
    toc: true
    page-layout: full



